export const riderData = [
  {
    name: "Demi Vollering",
    country: "Netherlands",
    team: "SD Worx",
    age: 26,
    height: "1.72m",
    specialty: "climbing",
    world_ranking: 1,
    social_media: {
      twitter: "https://twitter.com/demivollering",
      instagram: "https://www.instagram.com/demivollering/",
      strava: "https://www.strava.com/athletes/16080090",
    },
  },
  {
    name: "Lorenna Wiebes",
    country: "Netherlands",
    team: "SD Worx",
    age: 24,
    height: "1.71m",
    specialty: "climbing",
    world_ranking: 2,
    social_media: {
      twitter: "https://twitter.com/lorenawiebes",
      instagram: "https://www.instagram.com/lorenawiebes/",
      strava: "https://www.strava.com/athletes/7703167",
    },
  },
  {
    name: "Annemiek van Vleuten",
    country: "Netherlands",
    team: "Movistar",
    age: 40,
    height: "1.68m",
    specialty: "Time Trial",
    world_ranking: 3,
    social_media: {
      twitter: "https://twitter.com/AvVleuten",
      instagram: "https://www.instagram.com/annemiekvanvleuten/",
      strava: "",
    },
  },
  {
    name: "Elisa Longo Borghini",
    country: "Italy",
    team: "Trek Segafreo",
    age: 31,
    height: "1.70m",
    specialty: "Time Trial",
    world_ranking: 4,
    social_media: {
      twitter: "https://twitter.com/ElisaLongoB",
      instagram: "https://www.instagram.com/elisalongob/",
      strava: "https://www.strava.com/pros/1189566",
    },
  },
];
